### ISSUE TITLE
Missing script tag in HTML file

### ISSUE THREAD

**Issue by LNKeat** [learn-co-curriculum/react-hooks-import-export-lab#2]
I'm not sure if this intentional, but I'd think not.  
There is not a script tag in the HTML file linking index.js, so the DOM won't render anything, although the instructions specifically say:  "Your goal is to fix the errors, and get our app to match this example:"

Perhaps that's an error that you want us to catch/fix (even though it's not in the tests).   I feel like that could be super frustrating or discouraging if someone doesn't catch it quickly enough

**Comment by ihollander** [comment]
Hi @LNKeat - for all React applications created with [Create React App](http://create-react-app.dev/), which is what we use for the labs and what you'll use for React projects, there is no direct reference to the index.js file in the index.html file. This is intentional - that index.js file is generated dynamically when your application runs, so there's no need for you to add a `<script>` tag and link it yourself. It's just one of those things that React takes care of for you!

This Stack Overflow answer has a good explanation: https://stackoverflow.com/a/42440000
